### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kumar-physics** [rcsb/py-mmcif#1]
My installation and tox test failed on Linux Mint(18.3) which is based on Ubuntu 16.04
I disabled py36 in tox.ini file and ran tox only for py27.  My python version 2.7.12 and gcc version 5.4.0
Its strange that the required python 3 version is above the repository version and required gcc version is below the repository version.
log file attached
Thanks
[py27-1.log](https://github.com/rcsb/py-mmcif/files/2160143/py27-1.log)

**Comment by kumar-physics** [comment]
I have upgraded my system to Mint 19,0 today. I deleted all the old files, cloned a fresh copy and ran tox. This time it failed on tests 


 `======================================================================
ERROR: IoAdapterCoreTests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: IoAdapterCoreTests
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/kumaran/git/OneDep/nmr_restraint_validation/depui/py-mmcif/mmcif/tests/IoAdapterCoreTests.py", line 36, in <module>
    from mmcif.io.IoAdapterCore import IoAdapterCore as IoAdapter
  File "mmcif/io/IoAdapterCore.py", line 56, in <module>
    from build.lib.mmciflib import ParseCifSimple, CifFile, ParseCifSelective, type, CifFileReadDef
ImportError: No module named build.lib.mmciflib


----------------------------------------------------------------------
Ran 67 tests in 81.201s

FAILED (errors=1)
ERROR: InvocationError: '/home/kumaran/git/OneDep/nmr_restraint_validation/depui/py-mmcif/.tox/py27/bin/python -m unittest discover --start-directory mmcif/tests/ --pattern *Tests.py'
___________________________________________________________________________ summary ____________________________________________________________________________
ERROR:   py36: commands failed
ERROR:   py27: commands failed
`

**Comment by jdwestbrook** [comment]
The source of the build issue with GCC 5.4 appears to be a link-time issue that will require 
some changes in the CMAKE configuration.  This is discussed further in the SO post 
https://stackoverflow.com/questions/39236917/using-gccs-link-time-optimization-with-static-linked-libraries.

The issue with running tests in  V14 was a TOX config issue on Linux that has been updated.

**Comment by jdwestbrook** [comment]
V0.18 will build on Ubuntu GCC 5.4 with python versions 2.7.15, 3.6.6, and 3.7.0.
