### ISSUE TITLE
Unclear how to build on Windows

### ISSUE THREAD

**Issue by sobolevnrm** [rcsb/py-mmcif#5]
Hello --

This code requires compilation of C/C++ libraries which does not appear to work on Win 10.  I received numerous errors when running `tox` on the code base.  Most of the errors appear to stem from:

```
CMake Error at CMakeLists.txt:50 (message):
      No current support for MSVC!
```

Why are the C/C++ libraries needed?  Is there additional functionality in this code that isn't covered in the original pure-Python code at http://mmcif.wwpdb.org/docs/sw-examples/python/src/pdbx.tar.gz ?   We have modernized the original pure-Python code in https://github.com/Electrostatics/mmcif_pdbx and would be happy to contribute it back to this repo, if you like.

**Comment by jdwestbrook** [comment]
Thanks for your comment. 

The current automated deployment and testing for this project is limited to Linux and Macos.  We welcome any contributions to extend this to Windows platforms.

You can access the pure Python functionality of this library without the compiled bits.   You could have a look at the examples in mmcif/tests/testIoAdapterPy.py for examples of this access path.
