### ISSUE TITLE
./initdocs.sh fails complaining about various Sphinx module missing

### ISSUE THREAD

**Issue by pdkovacs** [rcsb/py-mmcif#6]
MacOS 10.15.5 (19F101)
conda 4.8.2

I am not sure of whether this is due to anaconda or MacOS, but the `./scripts/initdocs.sh`  seems to require various Sphinx modules which aren't installed with the default Sphinx installation. Command line to install which I ended up needing is
```
conda install Sphinx recommonmark sphinx_bootstrap_theme sphinxcontrib-napoleon
```
Even if this is conda specific, it may be worth mentioning it in the README.

**Comment by jdwestbrook** [comment]
Thank you for pointing out the problem.  We will post a fix for these dependencies shortly.
