### ISSUE TITLE
Convert mmCIF to binary Cif

### ISSUE THREAD

**Issue by AlessioDelConte** [rcsb/py-mmcif#9]
Hello,
how can I convert an mmCIF to a binaryCiF using this library?

Thanks

**Comment by josemduarte** [comment]
This test has an example on how to read cif and write out bcif:

https://github.com/rcsb/py-mmcif/blob/master/mmcif/tests/testBinaryCifWriter.py

**Comment by AlessioDelConte** [comment]
Thanks, I managed to do this!

**Comment by ljmartin** [comment]
@AlessioDelConte could you please share your approach to this? The test function is a bit opaque to me. 
Alternatively @josemduarte, if you have a minimum viable example to write a file or string in CIF format into bCIF, that would be really helpful! 
Thanks
